config/routes.rb
Rails.application.routes.draw do
  resources :customizations
  resources :customizations
  resources :materials
  resources :formulas
  resources :categories
  resources :food_categories
  devise_for :admins
  resources :products
  resources :sales

  resources :charges, only: [:create]
  post '/charge', to: 'charges#create'
  post '/buy', to: 'charges#create',   as: :buy
  get  '/thanks/:guid',   to: 'charges#thanks',   as: :thanks

  post '/cart/checkout' => 'cart#checkout'
  post '/configure/cart' => 'cart#configure'
  post '/create_payment_intent' => 'cart#create_payment_intent'

  get '/success/:session_id' => "cart#success"

  root 'pages#home'

end

app/models/material.rb
class Material < ActiveRecord::Base
    belongs_to :formula
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:generic, :specific, :cost, :makes, :position, :formula_id)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :generic %><br>
    <%= f.text_field :generic %>
  </div>
  <div class="field">
    <%= f.label :specific %><br>
    <%= f.text_field :specific %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :makes %><br>
    <%= f.text_field :makes %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :formula_id %><br>
    <%= f.number_field :formula_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Generic</th>
      <th>Specific</th>
      <th>Cost</th>
      <th>Makes</th>
      <th>Position</th>
      <th>Formula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.generic %></td>
        <td><%= material.specific %></td>
        <td><%= material.cost %></td>
        <td><%= material.makes %></td>
        <td><%= material.position %></td>
        <td><%= material.formula_id %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Generic:</strong>
  <%= @material.generic %>
</p>

<p>
  <strong>Specific:</strong>
  <%= @material.specific %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @material.cost %>
</p>

<p>
  <strong>Makes:</strong>
  <%= @material.makes %>
</p>

<p>
  <strong>Position:</strong>
  <%= @material.position %>
</p>

<p>
  <strong>Formula:</strong>
  <%= @material.formula_id %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>