config/routes.rb
Rails.application.routes.draw do
  resources :customizations
  resources :customizations
  resources :materials
  resources :formulas
  resources :categories
  resources :food_categories
  devise_for :admins
  resources :products
  resources :sales

  resources :charges, only: [:create]
  post '/charge', to: 'charges#create'
  post '/buy', to: 'charges#create',   as: :buy
  get  '/thanks/:guid',   to: 'charges#thanks',   as: :thanks

  post '/cart/checkout' => 'cart#checkout'
  post '/configure/cart' => 'cart#configure'
  post '/create_payment_intent' => 'cart#create_payment_intent'

  get '/success/:session_id' => "cart#success"

  root 'pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :sales
	belongs_to :category

	has_many :formulas

	has_many :customizations

	def self.tag(tag)
		array = []
		Product.all.each do |p|
			if p.tags.present?
				if p.tags.include? tag
					array.push(p)
				end
			end	
		end
		return array
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :title %>
<%= f.text_field :title, :class => "form-control" %>
<%= f.label :image_url %>
<%= f.text_field :image_url, :class => "form-control" %>
<%= f.label :description %>
<%= f.text_area :description, :class => "form-control" %>
<%= f.label :price %>
<%= f.number_field :price, :class => "form-control" %>
<%= f.label :minimum %>
<%= f.number_field :minimum, :class => "form-control" %>
<%= f.label :maximum %>
<%= f.number_field :maximum, :class => "form-control" %>
<%= f.label :group_size %>
<%= f.number_field :group_size, :class => "form-control" %>

<%= f.select(:category_id, Category.all.collect {|u| [u.title, u.id]}, :prompt => 'Select', :class => "form-control") %>


<%= f.text_field :tags, :class => "form-control" %>

<br>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

<script>
  $("textarea").froalaEditor({})
</script>

app/views/products/_solo.html.erb
<%= form_tag charges_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
	
	<h1>$<span class="total-cost"><%= @product.price * @product.minimum %></span></h1>
	<h3>Order Now:</h3>

  <br>
  <p>Requests (optional):</p>
  <textarea name="requests" class="form-control"></textarea>
  <br>

  <input type="number" name="product_id" value="<%= @product.id %>" class="hidden">
    <span class="btn btn-pink btn-lg btn-block buy-now">
		Place Order
	</span>
  <div class="stripe-it hide">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="<%= @product.title %>"
    data-description="2 widgets ($20.00)"
    data-amount="<%= @product.price * 100 %>">
  </script>
  </div>
<% end %>

<hr>

<script>
	$(".buy-now").on("click", function(){
		$(".stripe-it").find("button").trigger("click");
	});

	$(".quantity").bind('input', function(){
		$(".total-cost").html($(this).val() * <%= @product.price %>);
	})
</script>

app/views/products/_with_quantity.html.erb
<style>
  
  .spinner {
    width: 119px;
    margin: 0 auto;
  }

  .btn-group button {
    font-size: 20px;
  }

  input#amount {
    width: 77px;
    text-align: center;
    background-color: #9866a9;
    color: #fff;
    display: block;
    font-size: 26px;
  }

  .ncrg {
    color: #ee7785;
  }

  .buy-now {
    /* display: none; */
  }
</style>

<%= form_tag charges_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
	 
   <h3>How Many?</h3>

   <div class="spinner">
<!-- 		<input type="number" id="amount" name="quantity" class="form-control" min="<%= @product.minimum %>" value="<%= @product.minimum %>" pattern="\d*"/> -->
<div class="btn-group" role="group" aria-label="Basic example" data-grp="<%= @product.group_size if @product.group_size.present? %>">
  <button type="button" class="btn btn-info minus-one">-</button>
  <button type="button" class="btn btn-primary quantity-count"><%= @product.minimum %></button>
  <button type="button" class="btn btn-info plus-one">+</button>
</div>

    </div>

  <hr>

	<h1 class="usd-cost">$<span class="total-cost"><%= @product.price * @product.minimum %></span></h1>

  <p class="requests-label">Requests (optional):</p>
  <textarea name="requests" class="form-control"></textarea>
  <br>

  <%= hidden_field_tag(:stripeToken) %>
  <%= hidden_field_tag(:stripeEmail) %>
  <%= hidden_field_tag(:quantity) %>

  <input type="number" name="product_id" value="<%= @product.id %>" class="hidden">
    <span class="btn btn-pink btn-lg btn-block buy-now">
		  Add To Cart
	  </span>
  </div>
<% end %>

<hr>


<script>

  changeTotal = function(){
    count = parseInt($(".quantity-count").html())
    $(".total-cost").html(count * <%= @product.price %>);
    $('input#quantity').val(parseInt($(".quantity-count").html()));
  }


  changeTotal()

  $(".plus-one").on("click", function(){
    current = parseInt($(".quantity-count").html())
    grp = parseInt($(".btn-group").attr("data-grp"))
    new_count = current + grp
    $(".quantity-count").html(new_count)
    changeTotal()
  })

  $(".minus-one").on("click", function(){
    current = parseInt($(".quantity-count").html())
    grp = parseInt($(".btn-group").attr("data-grp"))
    new_count = current - grp
    if (new_count > <%= @product.minimum - 1 %>) {
      $(".quantity-count").html(new_count)
      changeTotal()
    }
  })

  // $("input#amount").bind('input', function(){
  //  $(".total-cost").html($(this).val() * <%= @product.price %>);
  // })



  $("body").on("click", ".buy-now", function(){
      cost = $(".total-cost").html()
    
      $.ajax({
          type: "POST",
          dataType: "json",
          url: '/configure/cart',
          contentType: 'application/json',
          data: JSON.stringify({ 
            config: "add_product",
            product_id: <%= @product.id %>,
            quantity: parseInt($(".quantity-count").html()),
            requests: $("textarea[name='requests']").val(),
            cost: cost,
            title: "<%= @product.title %>",
            _method:'post' 
          }),
          success: function(res){
            console.log(res)
            cart = res["cart"]
            populateCart(cart)
          }
      })
  })


  $( ".phone-number" ).on("keyup", function( event ) {
    if ( $(".phone-number").val().length > 6 ) {
      btnVisibility(true)
    } else {
      btnVisibility(false)
    }
  });

  function btnVisibility(bool){
    console.log(bool)
    if (bool) {
      $(".buy-now").show()
    } else {
      $(".buy-now").hide()
    }
  }
</script>

app/views/products/edit.html.erb
<style>
    label {
        font-weight: bold;
        font-size: 30px;
        margin-top: 20px;
    }
</style>

<h1>Editing Product</h1>

<hr>


<label>Title:</label>
<input type="text" class="form-control" name="title" value="<%= @product.title %>" />


<label>Image Url:</label>
<input type="text" class="form-control" name="image_url" value="<%= @product.image_url %>" />



<label>Description:</label>
<textarea class="form-control" name="description" value="<%= @product.description %>"></textarea>

<label>Price:</label>
<input type="number" class="form-control" name="price" value="<%= @product.price %>" />

<label>Minimum:</label>
<input type="number" class="form-control" name="minimum" value="<%= @product.minimum %>" />

<label>Maximum:</label>
<input type="number" class="form-control" name="maximum" value="<%= @product.maximum %>" />


<label>Group Size:</label>
<input type="number" class="form-control" name="group_size" value="<%= @product.group_size %>" />

<label>Category:</label>
<select name="category_id" id="" class="form-control">
    <% Category.all.each do |category| %>
        <option <%= 'selected' if @product.category_id == category.id %>  value="<%= category.id %>"><%= category.title %></option>
    <% end %>
</select>

<script>
var placeholderTypeWatchOptions = {
    callback: function (value) { 
        saveProduct()
    },
    wait: 750,
    highlight: true,
    allowSubmit: false,
    captureLength: 0
}

$("[name]").typeWatch( placeholderTypeWatchOptions );
$("body").on("change", "select", function(){
    saveProduct()
})


function saveProduct(){

    hash = {}
    hash["_method"] = "post"
    $("input, select, textarea").each(function(){
        hash[$(this).attr("name")] = $(this).val()
    })
    
    $.ajax({
        type: "PUT",
        dataType: "json",
        url: '/products/<%= @product.id %>',
        contentType: 'application/json',
        data: JSON.stringify(hash),
        success: function(res){
            console.log(res)
        }
    })
}

</script>

<hr>



<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><a href="/products/<%= product.id %>"><%= product.title %></a></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Product', new_product_path %>

<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="pswp__bg"></div>
    <div class="pswp__scroll-wrap">
 
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>
 
        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <div class="pswp__counter"></div>
                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                <button class="pswp__button pswp__button--share" title="Share"></button>
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div> 
            </div>
            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>
            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>
            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>
    </div>
</div>

<%= render "products/photoswipe/script" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<style>
	.shopfront img {
		width: 350px;
		margin: 0 auto;
	}

	.btn-pink {
		background-color :#ee7785;
		color: #fff;
		transition: 1s;
	}

	.btn-pink:hover {
		background-color :#da4e5e;
		color: #fff;

	}

	.btn a,.btn a:hover,.btn a:visited,.btn a:focus {
		color: #fff;
	}

	form {
		background-color: #ffdbdb;
    	padding: 25px;
	}

	form h1, h3 {
		color: rgba(102, 45, 145, 0.67);
		text-align: center;
	}

	.shopfront {
		max-width: 350px;
		margin: 0 auto;
	}

	.description {
		text-align: left;
		padding: 10px 10px;
		border: 1px solid #000;
		margin: 10px 0;
	}

</style>


<div class="shopfront show-product">

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/"><%= @product.category.title %></a></li>
  <li class="breadcrumb-item active"><%= @product.title %></li>
</ol>

	<img src="<%= @product.image_url %>" class="img-responsive" alt="">
<h1 class="product-title">
	<%= @product.title.gsub(/\(/, "<br>(").html_safe %>
</h1>

<% if @product.description.present? %>
	<section class="description product-description">
		<%= @product.description.html_safe %>
	</section>
<% end%>

<% if @product.minimum && @product.minimum > 0 %>
	<%= render "products/with_quantity"%>
<% else %>
	<%= render "products/solo"%>
<% end %>


<% if admin_signed_in? %>
	<hr>
	<%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %>
<% end %>

</div>